version: '3'

services:
  sensor_statistics:
    image: sensor_statistics
    build: .
    volumes:
      - ./app:/home/interviewer/app:rw
      - ./sbt/.ivy:/home/interviewer/.ivy:rw
      - ./sbt/.ivy2:/home/interviewer/.ivy2:rw
      - ./sbt/.sbt:/home/interviewer/.sbt:rw
